# Generated by Django 4.0.3 on 2022-03-04 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
                ('client', models.CharField(max_length=100)),
                ('minutes', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
