# Generated by Django 4.0.3 on 2022-03-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='role',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='work',
            name='task',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='work',
            name='work',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='client',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='employee',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='work',
            name='minutes',
            field=models.IntegerField(blank=True),
        ),
    ]
