# Generated by Django 4.0.3 on 2022-03-08 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_timesheet_work_timesheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='timesheet',
        ),
    ]
